"use client";

import { useState } from "react";
import styles from "./careers.module.css";

const roles = [
  { title: "Frontend Engineer", team: "Engineering", mission: "Make event discovery, ticketing, and organizer tools fast, responsive, and accessible.", work: ["Build polished React and Next.js experiences", "Improve mobile performance and accessibility", "Collaborate with design and backend engineering"], skills: "React, TypeScript, responsive UI, and thoughtful attention to performance." },
  { title: "Backend Engineer", team: "Engineering", mission: "Build reliable systems behind purchases, event operations, and organizer workflows.", work: ["Develop secure APIs and data models", "Improve payment fulfillment and reconciliation", "Build monitoring and dependable recovery paths"], skills: "TypeScript, APIs, data modeling, and experience with payment or event-driven systems." },
  { title: "Quality & Reliability Engineer", team: "Engineering", mission: "Help every release feel dependable—from the first search to the event entrance.", work: ["Test attendee and organizer journeys", "Create practical regression coverage", "Investigate bugs and improve release confidence"], skills: "Browser testing, clear bug reports, automation, and a focus on customer impact." },
  { title: "Product Designer", team: "Product & Design", mission: "Turn complex event workflows into experiences people enjoy using.", work: ["Design attendee and organizer journeys", "Develop accessible interfaces and reusable patterns", "Validate ideas with user feedback"], skills: "A portfolio showing interaction design, visual craft, and practical problem solving." },
  { title: "Product Manager", team: "Product & Design", mission: "Connect customer needs to clear priorities and meaningful product improvements.", work: ["Gather attendee and organizer feedback", "Define focused requirements and success measures", "Partner with engineering and design to deliver improvements"], skills: "Product judgment, clear communication, and experience translating needs into shipped work." },
  { title: "Data & Insights Analyst", team: "Growth & Community", mission: "Help us understand discovery, conversion, and the experiences that bring people back.", work: ["Build actionable product and growth reporting", "Evaluate experiments and conversion funnels", "Use privacy-conscious analytics to inform decisions"], skills: "SQL or analytics tools, experiment analysis, and the ability to explain findings clearly." },
  { title: "Growth Marketing Specialist", team: "Growth & Community", mission: "Introduce FunctionHour to the people and communities it can serve.", work: ["Plan and measure campaigns", "Develop creative messaging and channel experiments", "Improve acquisition and organizer activation"], skills: "Campaign execution, creative testing, and a practical grasp of marketing measurement." },
  { title: "Community & Partnerships Specialist", team: "Growth & Community", mission: "Build relationships with organizers, venues, and local communities.", work: ["Identify and connect with potential partners", "Support organizer onboarding", "Develop community collaborations and collect feedback"], skills: "Relationship building, outreach, and experience with events or community programs." },
  { title: "Customer Experience Specialist", team: "Operations", mission: "Make sure attendees and organizers feel supported when they need help.", work: ["Handle ticket, account, and event support", "Document recurring issues and improve help content", "Coordinate resolutions with operations and product"], skills: "Empathetic communication, careful follow-through, and customer support experience." },
  { title: "Event Operations Specialist", team: "Operations", mission: "Help organizers run smoother events with dependable processes and tools.", work: ["Support event setup and check-in workflows", "Improve operational guidance and documentation", "Coordinate organizer issues across the team"], skills: "Event operations, organization, and a calm approach to practical problem solving." },
  { title: "Marketing Intern — Content & Social", team: "Internships", mission: "Build a portfolio of creative work that helps people discover their next experience.", work: ["Create social content and event storytelling", "Help plan a content calendar", "Review campaign results with a supervisor each month"], skills: "Interest in marketing, strong writing or visual storytelling, and sample creative work." },
  { title: "Marketing Intern — Community & Campaigns", team: "Internships", mission: "Learn how community outreach and marketing campaigns come together.", work: ["Research communities, venues, and outreach opportunities", "Support campaign coordination and reporting", "Document learning goals and progress in monthly reviews"], skills: "Curiosity, communication, organization, and an interest in events and community marketing." },
];
const teams = ["All teams", "Engineering", "Product & Design", "Growth & Community", "Operations", "Internships"];

export default function CareersClient() {
  const [team, setTeam] = useState("All teams");
  const [search, setSearch] = useState("");
  const filtered = roles.filter((role) => (team === "All teams" || role.team === team) && `${role.title} ${role.team} ${role.mission}`.toLowerCase().includes(search.trim().toLowerCase()));
  return <section className={styles.jobs} id="opportunities" aria-labelledby="jobs-heading">
    <div className={styles.jobsHeading}><div><p className={styles.eyebrow}>FIND YOUR NEXT CHAPTER</p><h2 id="jobs-heading">A role for your kind of energy.</h2></div><span className={styles.count}>10 team roles + 2 internships</span></div>
    <p className={styles.jobsIntro}>Explore our opportunities. All roles are remote; location eligibility, schedule, compensation, and engagement terms will be confirmed during the initial conversation.</p>
    <div className={styles.filters}><label>Search roles<input type="search" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Title or keyword" /></label><label>Team<select value={team} onChange={(event) => setTeam(event.target.value)}>{teams.map((item) => <option key={item}>{item}</option>)}</select></label></div>
    <p className={styles.resultCount} role="status">{filtered.length} {filtered.length === 1 ? "opportunity" : "opportunities"}</p>
    <div className={styles.roleList}>{filtered.map((role) => <details className={styles.role} key={role.title}><summary><div><p>{role.team} / Remote{role.team === "Internships" ? " / 1 opening" : ""}</p><h3>{role.title}</h3></div><span className={styles.plus} aria-hidden="true">+</span></summary><div className={styles.roleBody}><p>{role.mission}</p><h4>What you’ll work on</h4><ul>{role.work.map((item) => <li key={item}>{item}</li>)}</ul><h4>What you’ll bring</h4><p>{role.skills}</p>{role.team === "Internships" && <div className={styles.credit}><strong>School-approved credit + monthly learning reviews</strong><p>We can coordinate learning objectives, supervision, and monthly progress documentation with your college. Credit eligibility, amount, and timing are determined by your school and require approval before you start. Monthly reviews do not guarantee monthly academic credit. Compensation and schedule will be discussed during the initial conversation.</p></div>}<a className={styles.apply} href={`mailto:operations@functionhour.com?subject=${encodeURIComponent(`FunctionHour application — ${role.title}`)}&body=${encodeURIComponent(`Hello FunctionHour team,\n\nI’m interested in the ${role.title} role.\n\nAbout me:\nPortfolio or résumé link:\nAvailability and location:\n${role.team === "Internships" ? "College and academic credit requirements:\n" : ""}\nThank you!`)}`}>Apply by email <span aria-hidden="true">↗</span></a><p className={styles.emailNote}>Opens your email app. Send your résumé or portfolio to <a href="mailto:operations@functionhour.com">operations@functionhour.com</a>. Your application is sent only when you send the email.</p></div></details>)}</div>
    {filtered.length === 0 && <div className={styles.empty}><h3>No matching roles yet.</h3><p>Try another search or browse all opportunities.</p><button onClick={() => { setSearch(""); setTeam("All teams"); }}>Show all roles</button></div>}
  </section>;
}
